### ISSUE TITLE
Exclude node_modules from `strict-component-imports`

### ISSUE THREAD

**Issue by cartogram** [Shopify/eslint-plugin-shopify#123] opened 2018-07-31 14:37 UTC
We can prevent the following from being flagged invalid by using the util identified in this discussion, https://github.com/Shopify/eslint-plugin-shopify/pull/117#issuecomment-408186647

```
import {Subscription} from 'apollo-client/util/Observable';
```

**Comment by alexandcote** [comment] 2020-03-27 22:04
This is not a bug anymore. Closing the issue.

**Closed as completed by alexandcote** 2020-03-27 22:04 UTC
